spring:
  application:
    name: feign-demo-server
  profiles:
    active: local
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://192.168.100.101:8761/eureka/
    registry-fetch-interval-seconds: 30
    instance-info-replication-interval-seconds: 30
    initial-instance-info-replication-interval-seconds: 30
